export default {
    "legend": [
        "Primary tissue",
        "Cell line"
    ],
    "xAxis": [
        "Prostate adenocarcinoma",
        "Gastric Adenocarcinoma",
        "Leiomyoma",
        "Rhabdomyosarcoma",
        "B-Cell Lymphoma",
        "Ependymoma",
        "Wilms Tumor",
        "Leukemia",
        "Glioblastoma",
        "Cutaneous T-Cell Lymphoma",
        "Multiple Myeloma",
        "Acute Myeloid Leukemia",
        "Ewing sacroma",
        "Diffuse Large B-Cell Lymphoma",
        "Precursor Cell Lymphoblastic Leukemia-Lymphoma",
        "Breast carcinoma",
        "Meningioma",
        "Epithelial Ovarian Cancer",
        "Diffuse Intrinsic Pontine Glioma",
        "Endometrial Carcinoma",
        "Chronic Lymphocytic Leukemia",
        "Osteosarcoma",
        "Melanoma",
        "Chordoma",
        "Rhabdoid Tumor",
        "Colorectal adenocarcinoma",
        "Breast invasive carcinoma",
        "Clear cell renal cell carcinoma",
        "Intracranial Aneurysm",
        "Bladder urothelial carcinoma",
        "Seminoma",
        "Sarcoma",
        "Hepatocellular Carcinoma",
        "Micropapillary Carcinoma",
        "Head and Neck Squamous Cell Carcinoma",
        "Lung Cancer",
        "Skin Cancer",
        "Neuroblastoma",
        "Brain Cancer",
        "Lymphoma",
        "Kidney Cancer",
        "Esophageal Cancer",
        "Liver Cancer",
        "Cervical cancer",
        "Chondroblastoma",
        "Pancreatic Cancer",
        "Germ Cell Cancer",
        "Thyroid Cancer",
        "Synovioma"
    ],
    "primary": [
        156,
        50,
        33,
        4,
        24,
        30,
        5,
        50,
        60,
        15,
        10,
        23,
        3,
        4,
        62,
        23,
        47,
        20,
        26,
        23,
        16,
        10,
        23,
        8,
        12,
        42,
        2,
        10,
        4,
        2,
        3,
        3,
        2,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "cell_line": [
        23,
        17,
        2,
        6,
        0,
        0,
        0,
        54,
        100,
        0,
        0,
        29,
        6,
        0,
        0,
        77,
        0,
        23,
        0,
        0,
        4,
        12,
        32,
        4,
        1,
        26,
        0,
        36,
        0,
        8,
        0,
        1,
        8,
        0,
        6,
        96,
        7,
        31,
        12,
        21,
        2,
        14,
        6,
        2,
        1,
        5,
        1,
        3,
        1
    ]
}
