export interface superRecord {
  "sample_id": string,
  "GSM_id": string,
  "enhancer_id": string,
  "chr": string,
  "start":number,
  "end":number,
  "length":string,
  "genome_annotate":string,
  "detail_annotation":string,
  "distance_to_TSS":string,
  "nearest_gene_name":string,
  "GWAS_SNP_number":number,
  "GTEx_eQTL_number":number,
  "cancer_eQTL_number":number,
}
